/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMajlisRouteImport } from './routes/_authenticated/majlis'
import { Route as AuthenticatedHeritageRouteImport } from './routes/_authenticated/heritage'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFamilyTreeRouteImport } from './routes/_authenticated/family-tree'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as AuthenticatedMembersUserIdRouteImport } from './routes/_authenticated/members.$userId'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMajlisRoute = AuthenticatedMajlisRouteImport.update({
  id: '/majlis',
  path: '/majlis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeritageRoute = AuthenticatedHeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyTreeRoute = AuthenticatedFamilyTreeRouteImport.update({
  id: '/family-tree',
  path: '/family-tree',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersUserIdRoute =
  AuthenticatedMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/family-tree': typeof AuthenticatedFamilyTreeRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/heritage': typeof AuthenticatedHeritageRoute
  '/majlis': typeof AuthenticatedMajlisRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/members/$userId': typeof AuthenticatedMembersUserIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/family-tree': typeof AuthenticatedFamilyTreeRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/heritage': typeof AuthenticatedHeritageRoute
  '/majlis': typeof AuthenticatedMajlisRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/members/$userId': typeof AuthenticatedMembersUserIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/family-tree': typeof AuthenticatedFamilyTreeRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/heritage': typeof AuthenticatedHeritageRoute
  '/_authenticated/majlis': typeof AuthenticatedMajlisRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/members/$userId': typeof AuthenticatedMembersUserIdRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/archive'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/family-tree'
    | '/finance'
    | '/heritage'
    | '/majlis'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/vault'
    | '/chat/$conversationId'
    | '/members/$userId'
    | '/trips/$tripId'
    | '/chat/'
    | '/members/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/archive'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/family-tree'
    | '/finance'
    | '/heritage'
    | '/majlis'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/vault'
    | '/chat/$conversationId'
    | '/members/$userId'
    | '/trips/$tripId'
    | '/chat'
    | '/members'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/archive'
    | '/_authenticated/chat'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/family-tree'
    | '/_authenticated/finance'
    | '/_authenticated/heritage'
    | '/_authenticated/majlis'
    | '/_authenticated/meetings'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/vault'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/members/$userId'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/chat/'
    | '/_authenticated/members/'
    | '/_authenticated/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/majlis': {
      id: '/_authenticated/majlis'
      path: '/majlis'
      fullPath: '/majlis'
      preLoaderRoute: typeof AuthenticatedMajlisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heritage': {
      id: '/_authenticated/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof AuthenticatedHeritageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family-tree': {
      id: '/_authenticated/family-tree'
      path: '/family-tree'
      fullPath: '/family-tree'
      preLoaderRoute: typeof AuthenticatedFamilyTreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$userId': {
      id: '/_authenticated/members/$userId'
      path: '/members/$userId'
      fullPath: '/members/$userId'
      preLoaderRoute: typeof AuthenticatedMembersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFamilyTreeRoute: typeof AuthenticatedFamilyTreeRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHeritageRoute: typeof AuthenticatedHeritageRoute
  AuthenticatedMajlisRoute: typeof AuthenticatedMajlisRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedMembersUserIdRoute: typeof AuthenticatedMembersUserIdRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFamilyTreeRoute: AuthenticatedFamilyTreeRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHeritageRoute: AuthenticatedHeritageRoute,
  AuthenticatedMajlisRoute: AuthenticatedMajlisRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedMembersUserIdRoute: AuthenticatedMembersUserIdRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
